/*
 * This source file was generated by the Gradle 'init' task
 */
package com.jeremy.goaltracker

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertNotNull

class AppTest {
    @Test
    fun testAppObjectExists() {
        // Check that the App object exists
        assertNotNull(App)
    }
}
