/*
 * This source file was generated by the Gradle 'init' goal
 */
package com.jeremy.goaltracker

import java.time.LocalDate
import java.time.DayOfWeek
import java.time.temporal.TemporalAdjusters
import java.util.Scanner
import com.jeremy.goaltracker.AnsiStyles as Ansi // BOLD, UNDERLINE, GREEN, RED, RESET, COLOR_RESET
import com.jeremy.goaltracker.GoalTimePeriod

object App {
    private val scanner = Scanner(System.`in`)
    private val goalTracker = GoalTracker()
    private var goalsOpen = false

    @JvmStatic
    fun main(args: Array<String>) {
        try {
            goalTracker.loadFromFile()
        } catch (e: Exception) {
            println("${Ansi.RED}Error: Saved goals could not be loaded.${Ansi.RESET}")
        }

        goalsOpen = true

        while (goalsOpen) {
            printMenu()
            val choice = scanner.nextLine().toIntOrNull()

            println("${Ansi.RESET}\n") // stop underline

            when (choice) {
                1 -> addGoal()
                2 -> goalTracker.listAllGoals()
                3 -> listGoalsByCategory()
                4 -> changeCompleteStatus()
                5 -> deleteGoal()
                6 -> closeGoalTracker()
                else -> println("${Ansi.RED}Invalid option.${Ansi.GREEN} Please try again & enter option number 1-6 from the menu.${Ansi.RESET}")
            }
        }
    }


    private fun printMenu() {
        println("\n${Ansi.BOLD} ==========================   _____________${Ansi.RESET}")
        println("${Ansi.BOLD}${Ansi.UNDERLINE}/       Goal Tracker       \\${Ansi.RESET}  |           |")
        println("|1) Add goal               |  |        /  |")
        println("|2) View all goals         |  |       /   |")
        println("|3) View goals by timeframe|  |      /    |")
        println("|4) Change goal status     |  |  \\  /     |")
        println("|5) Remove a goal          |  |   \\/      |")
        println("|6) Exit                   |  |___________|")
        println("${Ansi.BOLD}'=========================='   -----------${Ansi.RESET}")
        print("${Ansi.BOLD} ---> Option Selection :  ${Ansi.RESET}${Ansi.UNDERLINE}")
    }

    private fun selectGoalTimePeriod(promptMessage: String): GoalTimePeriod {
        var category: GoalTimePeriod? = null
        while (category == null) {
            println("${Ansi.GREEN}${Ansi.BOLD}Select the goal time period $promptMessage: ${Ansi.RESET}")
            GoalTimePeriod.entries.reversed().forEachIndexed { i, period ->
                println("${i + 1}) ${period.name}")
            }
            print("${Ansi.GREEN}${Ansi.BOLD}Time Period Selection: ${Ansi.RESET}${Ansi.UNDERLINE}")
            val input = scanner.nextLine().toIntOrNull()
            category = when (input) {
                1 -> GoalTimePeriod.DAILY
                2 -> GoalTimePeriod.WEEKLY
                3 -> GoalTimePeriod.MONTHLY
                4 -> GoalTimePeriod.YEARLY
                5 -> GoalTimePeriod.DECADE
                6 -> GoalTimePeriod.LIFETIME
                else -> {
                    println("\n${Ansi.RED}Invalid option. Please enter 1-6.${Ansi.RESET}")
                    null
                }
            }
        }
        return category
    }

    private fun getStartDate(): LocalDate {
        // Flexible date entry with defaults from today
        var startDate: LocalDate? = null
        val today = LocalDate.now()
        while (startDate == null) {
            print("${Ansi.GREEN}${Ansi.BOLD}Enter the start date for the goal time period (YYYY-MM-DD, MM-DD, DD, or ENTER = [default: today]): ${Ansi.RESET}")
            val input = scanner.nextLine().trim()            
            startDate = when {
                input.isEmpty() -> today // empty input -> today
                input.matches(Regex("""\d{1,2}""")) -> {
                    // Only day provided
                    today.withDayOfMonth(input.toInt())
                }
                input.matches(Regex("""\d{1,2}-\d{1,2}""")) -> {
                    // Month-Day provided
                    val parts = input.split("-").map { it.toInt() }
                    LocalDate.of(today.year, parts[0], parts[1])
                }
                input.matches(Regex("""\d{4}-\d{1,2}-\d{1,2}""")) -> {
                    // Full date provided
                    try { LocalDate.parse(input) } catch (e: Exception) { null }
                }
                else -> null
            }
            if (startDate == null) {
                println("${Ansi.RED}Invalid date format. Use YYYY-MM-DD, MM-DD, or DD.${Ansi.RESET}")
            }
        }
        return startDate
    }

    private fun getEndDate(period: GoalTimePeriod, startDate: LocalDate): LocalDate {
        return when (period) {
            GoalTimePeriod.DAILY -> startDate
            GoalTimePeriod.WEEKLY -> startDate.with(TemporalAdjusters.nextOrSame(DayOfWeek.SUNDAY))
            GoalTimePeriod.MONTHLY -> startDate.with(TemporalAdjusters.lastDayOfMonth())
            GoalTimePeriod.YEARLY -> startDate.with(TemporalAdjusters.lastDayOfYear())
            GoalTimePeriod.DECADE -> startDate.plusYears(10)
            GoalTimePeriod.LIFETIME -> startDate.plusYears(100)
        }
    }

    private fun addGoal() {
        // Goal Time Period Selection from User
        val promptInsert = "(1-6)"
        val timePeriod = selectGoalTimePeriod(promptInsert)
        println("${Ansi.RESET}You will be adding a goal to the goal time period of - ${Ansi.UNDERLINE}$timePeriod${Ansi.RESET}")  
        // Short Goal Label Entry from User
        print("${Ansi.GREEN}${Ansi.BOLD}Enter a short goal label: ${Ansi.RESET}")
        val label = scanner.nextLine()
        // Detailed Goal Description Entry from User
        print("${Ansi.GREEN}${Ansi.BOLD}Enter a detailed goal description: ${Ansi.RESET}")
        val description = scanner.nextLine()
        // Goal Period Start Date Entry from User
        var startDate = getStartDate()
        // Goal Priority Entry from User
        var priority: Int? = null
        while (priority == null) {
            print("${Ansi.GREEN}${Ansi.BOLD}Enter goal priority - [1] represents highest priority (1-5): ${Ansi.RESET}")
            priority = scanner.nextLine().toIntOrNull()
            if (priority == null || priority !in 1..5) {
                println("${Ansi.RED}Priority must be a whole number from 1 to 5.${Ansi.RESET}")
                priority = null
            }
        }
        // Show the goal before adding
        print("Are you sure you want to add this goal? (y/n): ")
        if (scanner.nextLine().trim().lowercase() != "y") {
            println("This goal was canceled.")
            return
        }
        goalTracker.addGoal(timePeriod, label, description, startDate, getEndDate(timePeriod, startDate), priority)
        println("\n${Ansi.BOLD}+ + + + + +")
        println("${Ansi.GREEN}Goal added.${Ansi.COLOR_RESET}")
        println("+ + + + + +${Ansi.RESET}")
        saveGoals() // SAVE CHANGES
    }

    private fun listGoalsByCategory() {
        // Goal Time Period Selection from User
        val promptInsert = "you wish to view goals for"
        var category = selectGoalTimePeriod(promptInsert)
        goalTracker.listGoalsByCategory(category)
    }

    private fun changeCompleteStatus() {
        // Goal Time Period Selection from User
        val promptInsert = "you wish to view goals for"
        var category = selectGoalTimePeriod(promptInsert)
        println("${Ansi.RESET}You will be changing a goal's status from the goal time period of - ${Ansi.UNDERLINE}$category${Ansi.RESET}")  
        // Goal Period Start Date Entry from User
        var startDate = getStartDate()
        val filteredGoals = goalTracker.listGoalSummary(category, startDate)
        if (filteredGoals.isEmpty()) return
      
        println("______________________________________________________")
        print("${Ansi.GREEN}${Ansi.BOLD}Enter number of the goal you want to change the completion status for: ${Ansi.RESET}")
        val goalNumber = scanner.nextLine().toIntOrNull()
        if (goalNumber == null || goalNumber !in 1..filteredGoals.size) {
            println("${Ansi.RED}Invalid selection.${Ansi.RESET}")
            return
        }
        val selectedGoal = filteredGoals[goalNumber - 1]
        goalTracker.toggleCompleteStatus(selectedGoal.id)
        println("${Ansi.BOLD}\n.................................")
        println("${Ansi.GREEN}Goal status successfully updated.${Ansi.RESET}")
        println("*********************************")
        saveGoals() // SAVE CHANGES
    }

    private fun deleteGoal() {
        // Goal Time Period Selection from User
        val promptInsert = "you want to remove a goal from"
        var category = selectGoalTimePeriod(promptInsert)
        println("${Ansi.RESET}You will be removing a goal from the goal time period of - ${Ansi.UNDERLINE}$category${Ansi.RESET}")       
        // Goal Period Start Date Entry from User
        var startDate = getStartDate()
        // Get the filtered list
        val matches = goalTracker.listGoalSummary(category, startDate)
        if (matches.isEmpty()) return

        println("______________________________________________________")
        print("${Ansi.GREEN}${Ansi.BOLD}Enter the number of goal you want to remove: ${Ansi.RESET}")
        val goalNumber = scanner.nextLine().toIntOrNull()
        if (goalNumber == null || goalNumber !in 1..matches.size) {
            println("${Ansi.RED}Invalid selection.${Ansi.RESET}")
            return
        }
        val goalToDelete = matches[goalNumber - 1]
        // Show the goal before deletion
        println("\n${Ansi.RED}${Ansi.BOLD}You have chosen to remove the following goal:${Ansi.RESET}")
        println(goalToDelete)
        print("Are you sure you want to remove this goal? (y/n): ")
        if (scanner.nextLine().trim().lowercase() != "y") {
            println("The removal of the goal was canceled.")
            return
        }
        // Perform the deletion
        goalTracker.deleteGoalById(goalToDelete.id)
        println("${Ansi.BOLD}\n..................................")
        println("${Ansi.GREEN}The goal was successfully removed!${Ansi.RESET}")
        println("**********************************")
        saveGoals() // SAVE CHANGES    
}

    private fun saveGoals() {
        try {
            goalTracker.saveToFile()
            println("${Ansi.BOLD}~~~~~~~~~~~~~~~~~~~")
            println("${Ansi.GREEN}Goal changes saved.${Ansi.COLOR_RESET}")
            println("~~~~~~~~~~~~~~~~~~~${Ansi.RESET}")
        } catch (e: Exception) {
            println("${Ansi.RED}Error saving goal changes.${Ansi.RESET}")
        }
    }

    private fun closeGoalTracker() {
        println("${Ansi.BOLD}-------------------------------------------")
        println("${Ansi.RED}Closing Goal Tracker ${Ansi.COLOR_RESET}... ${Ansi.GREEN}see you next time!${Ansi.COLOR_RESET}")
        println("-------------------------------------------\n${Ansi.RESET}")
        goalsOpen = false
    }
}